### ISSUE TITLE
ModuleNotFoundError: No module named 'setuptools.command.test' as of latest setuptools package release

### ISSUE THREAD

**Issue by DanielLeone** [beautifier/js-beautify#2301]
The latest [setuptools==72.0.0](https://github.com/pypa/setuptools/releases/tag/v72.0.0) release breaks the python package install, because of a deprecation removal https://setuptools.pypa.io/en/stable/history.html#deprecations-and-removals

You can see by either running `pip install jsbeautifier` on a fresh install using the public PyPI package, or running `make py` in this repo.

```sh
$ pip install --no-cache jsbeautifier
Collecting jsbeautifier
  Downloading jsbeautifier-1.15.1.tar.gz (75 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "/Users/danielleone/.envs/test/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/danielleone/.envs/test/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/danielleone/.envs/test/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/59/bys8flwx4ns3y422p1y5pdnm0000gn/T/pip-build-env-0x9kjfoz/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/private/var/folders/59/bys8flwx4ns3y422p1y5pdnm0000gn/T/pip-build-env-0x9kjfoz/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/59/bys8flwx4ns3y422p1y5pdnm0000gn/T/pip-build-env-0x9kjfoz/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/59/bys8flwx4ns3y422p1y5pdnm0000gn/T/pip-build-env-0x9kjfoz/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 9, in <module>
      ModuleNotFoundError: No module named 'setuptools.command.test'
      [end of output]
```

----

Workaround for using this package in the mean time is to use:

`PIP_CONSTRAINT='constraints.txt' pip install my-package` where `constraints.txt` is:

```
setuptools==71.1.0
```

NOTE: you must use the `PIP_CONSTRAINT` env var and not the `pip -c` flag as the `-c` flag does not propagate to subprocesses of which is being used here.

**Comment by JoeyStk** [comment]
I ran into this issue as well

**Comment by cclauss** [comment]
Proof in
* #2303

**Comment by josephd-envsys** [comment]
Can confirm this issue, we are seeing it across multiple repositories.
We use `uv` to manage dependencies and venv packages. 

It looks to me like `cssbeautifier`/`jsbeautifier` packages are using an older build system, because we get this appear in the install log:
```bash
Calling `setuptools.build_meta:__legacy__.get_requires_for_build_wheel()`
```

See below for the full verbose output of `uv pip install cssbeautifier --refresh -vv`:
```bash
❯ uv pip install cssbeautifier --refresh -vv
    0.000023s DEBUG uv uv 0.2.12
 uv_requirements::specification::from_source source=cssbeautifier
    0.002890s DEBUG uv_toolchain::discovery Searching for Python interpreter in virtual environments
    0.029504s DEBUG uv_toolchain::discovery Found cpython 3.10.12 at `/home/joseph/repos/optioat_web/venv/bin/python3` (active virtual environment)
    0.029523s DEBUG uv::commands::pip::install Using Python 3.10.12 environment at venv/bin/python3
    0.029546s DEBUG uv_fs Acquired lock for `venv`
    0.030737s DEBUG uv::commands::pip::install At least one requirement is not satisfied: cssbeautifier
 uv_client::linehaul::linehaul 
    0.031030s DEBUG uv_client::base_client Using request timeout of 30s
 uv_resolver::flat_index::from_entries 
 uv_resolver::resolver::solve 
   uv_resolver::resolver::solve_tracked 
      0.032245s   0ms DEBUG uv_resolver::resolver Solving with installed Python version: 3.10.12
     uv_resolver::resolver::choose_version package=root
     uv_resolver::resolver::get_dependencies_forking package=root, version=0a0.dev0
       uv_resolver::resolver::get_dependencies package=root, version=0a0.dev0
          0.032275s   0ms DEBUG uv_resolver::resolver Adding direct dependency: cssbeautifier*
     uv_resolver::resolver::choose_version package=cssbeautifier
 uv_resolver::resolver::process_request request=Versions cssbeautifier
   uv_client::registry_client::simple_api package=cssbeautifier
     uv_client::cached_client::get_cacheable 
       uv_client::cached_client::read_and_parse_cache file=/home/joseph/.cache/uv/simple-v9/pypi/cssbeautifier.rkyv
 uv_resolver::resolver::process_request request=Prefetch cssbeautifier *
 uv_client::cached_client::from_path_sync path="/home/joseph/.cache/uv/simple-v9/pypi/cssbeautifier.rkyv"
        0.032806s   0ms DEBUG uv_client::cached_client Found stale response for: https://pypi.org/simple/cssbeautifier/
        0.032849s   0ms DEBUG uv_client::cached_client Sending revalidation request for: https://pypi.org/simple/cssbeautifier/
       uv_client::cached_client::revalidation_request url="https://pypi.org/simple/cssbeautifier/"
        0.072966s  40ms DEBUG uv_client::cached_client Found not-modified response for: https://pypi.org/simple/cssbeautifier/
       uv_client::cached_client::refresh_cache file=/home/joseph/.cache/uv/simple-v9/pypi/cssbeautifier.rkyv
   uv_resolver::version_map::from_metadata 
   uv_distribution::distribution_database::get_or_build_wheel_metadata dist=cssbeautifier==1.15.1
        0.073437s  41ms DEBUG uv_resolver::resolver Searching for a compatible version of cssbeautifier (*)
        0.073456s  41ms DEBUG uv_resolver::resolver Selecting: cssbeautifier==1.15.1 (cssbeautifier-1.15.1.tar.gz)
     uv_resolver::resolver::get_dependencies_forking package=cssbeautifier, version=1.15.1
       uv_resolver::resolver::get_dependencies package=cssbeautifier, version=1.15.1
    0.073524s DEBUG uv_fs Acquired lock for `/home/joseph/.cache/uv/built-wheels-v3/pypi/cssbeautifier/1.15.1`
     uv_client::cached_client::get_serde 
       uv_client::cached_client::get_cacheable 
         uv_client::cached_client::read_and_parse_cache file=/home/joseph/.cache/uv/built-wheels-v3/pypi/cssbeautifier/1.15.1/revision.http
 uv_client::cached_client::from_path_sync path="/home/joseph/.cache/uv/built-wheels-v3/pypi/cssbeautifier/1.15.1/revision.http"
          0.073753s   0ms DEBUG uv_client::cached_client Found fresh response for: https://files.pythonhosted.org/packages/e5/66/9bfd2d69fb4479d38439076132a620972939f7949015563dce5e61d29a8b/cssbeautifier-1.15.1.tar.gz
     uv_distribution::source::build_metadata dist=cssbeautifier==1.15.1
        0.073786s   0ms DEBUG uv_distribution::source Preparing metadata for: cssbeautifier==1.15.1
        0.073811s   0ms DEBUG uv_distribution::source No static `PKG-INFO` available for: cssbeautifier==1.15.1 (PkgInfo(UnsupportedMetadataVersion("2.1")))
        0.073859s   0ms DEBUG uv_distribution::source No static `pyproject.toml` available for: cssbeautifier==1.15.1 (PyprojectToml(FieldNotFound("project")))
       uv_dispatch::setup_build version_id="cssbeautifier==1.15.1", subdirectory=None
          0.073949s   0ms  INFO uv_virtualenv::bare Ignoring empty directory
 uv_resolver::resolver::solve 
   uv_resolver::resolver::solve_tracked 
      0.074357s   0ms DEBUG uv_resolver::resolver Solving with installed Python version: 3.10.12
     uv_resolver::resolver::choose_version package=root
     uv_resolver::resolver::get_dependencies_forking package=root, version=0a0.dev0
       uv_resolver::resolver::get_dependencies package=root, version=0a0.dev0
          0.074387s   0ms DEBUG uv_resolver::resolver Adding direct dependency: setuptools>=40.8.0
         uv_resolver::resolver::process_request request=Versions setuptools
     uv_resolver::resolver::choose_version package=setuptools
           uv_client::registry_client::simple_api package=setuptools
             uv_client::cached_client::get_cacheable 
               uv_client::cached_client::read_and_parse_cache file=/home/joseph/.cache/uv/simple-v9/pypi/setuptools.rkyv
         uv_resolver::resolver::process_request request=Prefetch setuptools >=40.8.0
 uv_client::cached_client::from_path_sync path="/home/joseph/.cache/uv/simple-v9/pypi/setuptools.rkyv"
                0.074959s   0ms DEBUG uv_client::cached_client Found stale response for: https://pypi.org/simple/setuptools/
                0.074962s   0ms DEBUG uv_client::cached_client Sending revalidation request for: https://pypi.org/simple/setuptools/
               uv_client::cached_client::revalidation_request url="https://pypi.org/simple/setuptools/"
                0.086245s  11ms DEBUG uv_client::cached_client Found not-modified response for: https://pypi.org/simple/setuptools/
               uv_client::cached_client::refresh_cache file=/home/joseph/.cache/uv/simple-v9/pypi/setuptools.rkyv
           uv_resolver::version_map::from_metadata 
           uv_distribution::distribution_database::get_or_build_wheel_metadata dist=setuptools==72.0.0
             uv_client::registry_client::wheel_metadata built_dist=setuptools==72.0.0
               uv_client::cached_client::get_serde 
                 uv_client::cached_client::get_cacheable 
                   uv_client::cached_client::read_and_parse_cache file=/home/joseph/.cache/uv/wheels-v1/pypi/setuptools/setuptools-72.0.0-py3-none-any.msgpack
        0.088130s  13ms DEBUG uv_resolver::resolver Searching for a compatible version of setuptools (>=40.8.0)
        0.088142s  13ms DEBUG uv_resolver::resolver Selecting: setuptools==72.0.0 (setuptools-72.0.0-py3-none-any.whl)
     uv_resolver::resolver::get_dependencies_forking package=setuptools, version=72.0.0
       uv_resolver::resolver::get_dependencies package=setuptools, version=72.0.0
 uv_client::cached_client::from_path_sync path="/home/joseph/.cache/uv/wheels-v1/pypi/setuptools/setuptools-72.0.0-py3-none-any.msgpack"
                    0.088299s   0ms DEBUG uv_client::cached_client Found fresh response for: https://files.pythonhosted.org/packages/2f/83/06edd551b4fdf6170dcbafeeed588a8909819e943905c182ebdc98835be8/setuptools-72.0.0-py3-none-any.whl.metadata
      0.088488s  14ms DEBUG uv_resolver::resolver::batch_prefetch Tried 1 versions: setuptools 1
         uv_dispatch::install resolution="setuptools==72.0.0", venv="/home/joseph/.cache/uv/environments-v0/.tmpiThhvB"
            0.088605s   0ms DEBUG uv_dispatch Installing in setuptools==72.0.0 in /home/joseph/.cache/uv/environments-v0/.tmpiThhvB
            0.088638s   0ms DEBUG uv_installer::plan Must revalidate requirement: setuptools
            0.088650s   0ms DEBUG uv_dispatch Downloading and building requirement for build: setuptools==72.0.0
           uv_installer::downloader::download total=1
             uv_installer::downloader::get_wheel name=setuptools==72.0.0, size=Some(2337262), url="https://files.pythonhosted.org/packages/2f/83/06edd551b4fdf6170dcbafeeed588a8909819e943905c182ebdc98835be8/setuptools-72.0.0-py3-none-any.whl"
               uv_distribution::distribution_database::get_or_build_wheel dist=setuptools==72.0.0
                 uv_client::cached_client::get_serde 
                   uv_client::cached_client::get_cacheable 
                     uv_client::cached_client::read_and_parse_cache file=/home/joseph/.cache/uv/wheels-v1/pypi/setuptools/setuptools-72.0.0-py3-none-any.http
 uv_client::cached_client::from_path_sync path="/home/joseph/.cache/uv/wheels-v1/pypi/setuptools/setuptools-72.0.0-py3-none-any.http"
                      0.088934s   0ms DEBUG uv_client::cached_client Found fresh response for: https://files.pythonhosted.org/packages/2f/83/06edd551b4fdf6170dcbafeeed588a8909819e943905c182ebdc98835be8/setuptools-72.0.0-py3-none-any.whl
            0.088984s   0ms DEBUG uv_dispatch Installing build requirement: setuptools==72.0.0
           uv_installer::installer::install num_wheels=1
          0.092725s  18ms DEBUG uv_build Calling `setuptools.build_meta:__legacy__.get_requires_for_build_wheel()`
         uv_build::run_python_script script="get_requires_for_build_wheel", python_version=3.10.12
error: Failed to download and build `cssbeautifier==1.15.1`
  Caused by: Failed to build: `cssbeautifier==1.15.1`
  Caused by: Build backend failed to determine extra requires with `build_wheel()` with exit status: 1
--- stdout:

--- stderr:
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "/home/joseph/.cache/uv/environments-v0/.tmpiThhvB/lib/python3.10/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=[])
  File "/home/joseph/.cache/uv/environments-v0/.tmpiThhvB/lib/python3.10/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
    self.run_setup()
  File "/home/joseph/.cache/uv/environments-v0/.tmpiThhvB/lib/python3.10/site-packages/setuptools/build_meta.py", line 497, in run_setup
    super().run_setup(setup_script=setup_script)
  File "/home/joseph/.cache/uv/environments-v0/.tmpiThhvB/lib/python3.10/site-packages/setuptools/build_meta.py", line 313, in run_setup
    exec(code, locals())
  File "<string>", line 9, in <module>
ModuleNotFoundError: No module named 'setuptools.command.test'
---
```

**Comment by josephd-envsys** [comment]
See https://github.com/pypa/setuptools/issues/4519 for other workarounds and more information on the issue. `uv` behaves differently when it comes to workarounds, for example.

**Comment by sorenwacker** [comment]
Strangely, I get this even when I explicitly install older versions of setuptools on GitHub actions.

**Comment by echoix** [comment]
@sorenwacker I think wheels are built in isolation, so it isn't influenced from what is installed globally before. It should use what is defined by that dependency's files (like pyproject.toml)

**Comment by sorenwacker** [comment]
I tried specifying different versions there as well. 

```
[build-system]
requires = ["setuptools<=69", "wheel", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"
```
But also this did lead to the same error. I just started with pyproject.toml files, so probably there is something wrong.

**Comment by echoix** [comment]
> I tried specifying different versions there as well. 
> 
> 
> 
> ```
> 
> [build-system]
> 
> requires = ["setuptools<=69", "wheel", "setuptools_scm[toml]>=6.2"]
> 
> build-backend = "setuptools.build_meta"
> 
> ```
> 
> But also this did lead to the same error. I just started with pyproject.toml files, so probably there is something wrong.
> 
> 
> 
> 

Your project can define that version, but your dependency (like this repo) can specify something else and use that in their isolated build.

**Comment by sorenwacker** [comment]
Oh, got you. Would that impact older versions as well?

**Comment by echoix** [comment]
> Oh, got you. Would that impact older versions as well? 

Wheel will follow the version specifications, so if it says greater or equal to a version, without upper bounding it to newer versions, it would respect that. I don't know for pip, but for uv they have a mode/option that will recreate the wheel using only versions that were available for a specified date, to reproduce correctly an older build. (When the package has correct date information available).

**Comment by sorenwacker** [comment]
Usually, it uses the version that is installed unless it does not fit into the specifed version range, in that case it would install a version that fits. But I don't see any logs where setuptools is replaced. If I understand you correctly, the downloaded wheel is already broken. So, then can only wait. I the the same error with different setuptools versions as well as different js-beautifier versions. Never seen such behavior before.

**Comment by sorenwacker** [comment]
Actually, this helped:
```
[build-system]
requires = ["setuptools<=69", "wheel", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"
```
changed to 
```
[build-system]
requires = ["setuptools<=69", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"
```

**Comment by IronTopi** [comment]
The problematic setuptools version `72.0.0` has been yanked yesterday and a fixed `72.1.0` has been released, see https://pypi.org/project/setuptools/#history

All our pipelines are back up again and passing without any workarounds!

**Comment by LecrisUT** [comment]
Even so, please remove the problematic import. It will still be removed in a future version. Heck, even migrate to `pyproject.toml` since there is nothing custom in `setup.py` other than that

**Comment by LecrisUT** [comment]
This issue is still relevant until #2304
